version: '2'

services:
  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
  redis:
    build: ./redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    user: '1000:1000'
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/data:/data
  web:
    image: nginx
    restart: unless-stopped
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ${SRC_ROOT}:/app
      - ./nginx/sites/${ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/${ENV}.default.conf:/etc/nginx/${ENV}.default.conf
    links:
      - php

  php:
    extends:
      file: base-php/base-php.yml
      service: base-php
    restart: unless-stopped
    working_dir: /app
    user: '1000:1000'
    volumes:
      - ${SRC_ROOT}:/app
    links:
      - db
      - redis
  nodejs:
    image: node:18-alpine
    working_dir: /app
    restart: unless-stopped
    stdin_open: true
    ports:
      - "${NODEJS_PORT}:3000"
    volumes:
      - ${SRC_ROOT}:/app
    links:
      - db
      - redis